import type { Metadata } from 'next'
import { nunito, robo } from '@/app/fonts'
import './globals.css'
import { RenderMounted } from '@/components/render-mounted'
import Header from '@/components/header/header'

export const metadata: Metadata = {
	title: 'Time&Spaces',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${robo.variable} ${nunito.variable} antialiased`}>
				<RenderMounted>
					<Header />
					<main>{children}</main>
				</RenderMounted>
			</body>
		</html>
	)
}
